command: docker mcp config
short: Obsolete
long: Obsolete
usage: docker mcp config
pname: docker mcp
plink: docker_mcp.yaml
deprecated: false
hidden: true
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

